"""Add column to indicate part number if split

Revision ID: 333f927c0057
Revises: 5b5772b8cabd
Create Date: 2016-07-15 11:25:05.294516

"""

# revision identifiers, used by Alembic.
revision = '333f927c0057'
down_revision = '5b5772b8cabd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archived_gazette', sa.Column('part', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archived_gazette', 'part')
    ### end Alembic commands ###
