"""Add column to indicate language special editions

Revision ID: 5b5772b8cabd
Revises: 9310964bece4
Create Date: 2016-07-15 09:35:05.453461

"""

# revision identifiers, used by Alembic.
revision = '5b5772b8cabd'
down_revision = '9310964bece4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archived_gazette', sa.Column('language_edition', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archived_gazette', 'language_edition')
    ### end Alembic commands ###
