"""Add page count field to ArchivedGazette

Revision ID: 788cdc88f188
Revises: c1465df276e2
Create Date: 2016-07-14 17:45:51.596215

"""

# revision identifiers, used by Alembic.
revision = '788cdc88f188'
down_revision = 'c1465df276e2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archived_gazette', sa.Column('pagecount', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archived_gazette', 'pagecount')
    ### end Alembic commands ###
