"""Change type field to referrer URL

Revision ID: 79330d9ee05c
Revises: f83c51f3257a
Create Date: 2016-07-07 11:15:11.326908

"""

# revision identifiers, used by Alembic.
revision = '79330d9ee05c'
down_revision = 'f83c51f3257a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gazettes', sa.Column('referrer', sa.String(), nullable=True))
    op.create_index(op.f('ix_gazettes_referrer'), 'gazettes', ['referrer'], unique=False)
    op.execute('update gazettes set referrer = type')
    op.alter_column('gazettes', 'referrer', nullable=False)
    op.drop_index('ix_gazettes_type', table_name='gazettes')
    op.drop_column('gazettes', 'type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gazettes', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_gazettes_type', 'gazettes', ['type'], unique=False)
    op.execute('update gazettes set type = referrer')
    op.alter_column('gazettes', 'type', nullable=False)
    op.drop_index(op.f('ix_gazettes_referrer'), table_name='gazettes')
    op.drop_column('gazettes', 'referrer')
    ### end Alembic commands ###
