"""Minimal ArchivedGazette model

Revision ID: c1465df276e2
Revises: f7c0f7ce21db
Create Date: 2016-07-14 11:16:14.732402

"""

# revision identifiers, used by Alembic.
revision = 'c1465df276e2'
down_revision = 'f7c0f7ce21db'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archived_gazette',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_uri', sa.String(), nullable=False),
    sa.Column('archive_path', sa.String(), nullable=False),
    sa.Column('publication_title', sa.String(), nullable=False),
    sa.Column('publication_subtitle', sa.String(), nullable=True),
    sa.Column('special_issue', sa.String(), nullable=True),
    sa.Column('issue_number', sa.Integer(), nullable=False),
    sa.Column('volume_number', sa.Integer(), nullable=False),
    sa.Column('jurisdiction_code', sa.String(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('unique_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('archive_path'),
    sa.UniqueConstraint('original_uri'),
    sa.UniqueConstraint('unique_id')
    )
    op.create_index(op.f('ix_web_scraped_gazette_referrer'), 'web_scraped_gazette', ['referrer'], unique=False)
    op.drop_index('ix_gazettes_referrer', table_name='web_scraped_gazette')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_gazettes_referrer', 'web_scraped_gazette', ['referrer'], unique=False)
    op.drop_index(op.f('ix_web_scraped_gazette_referrer'), table_name='web_scraped_gazette')
    op.drop_table('archived_gazette')
    ### end Alembic commands ###
