"""Add gazette type field

Revision ID: f83c51f3257a
Revises: 
Create Date: 2016-07-06 16:51:26.377233

"""

# revision identifiers, used by Alembic.
revision = 'f83c51f3257a'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gazettes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_uri', sa.String(), nullable=False),
    sa.Column('store_path', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('published_date', sa.Date(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_uri'),
    sa.UniqueConstraint('store_path')
    )
    op.create_index(op.f('ix_gazettes_type'), 'gazettes', ['type'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gazettes_type'), table_name='gazettes')
    op.drop_table('gazettes')
    ### end Alembic commands ###
